### ISSUE TITLE
ThreadResolverWorker ArgumentError: wrong number of arguments (given 3, expected 2)

### ISSUE THREAD

**Issue by MikeHuntington** [nanos/FediFetcher#67] opened 2023-07-30 19:05 UTC
I've noticed when using FediFetcher, I'm getting a lot of failed queued processing. After having FediFetcher running for a day or 2, I have about 9,999 dead items.

![278e709cc12b07e8](https://github.com/nanos/FediFetcher/assets/2466745/0397ae81-f805-497a-9dbf-790cbc8c7604)

**Comment by nanos** [comment] 2023-07-31 08:06
Hm. I'm sorry, but I must admit that I'm not convinced that this is FediFetcher causing this:

Firstly, because FediFetcher doesn't do anything with Mastodon jobs directly: it simply uses the Mastodon API. As such, even if it was a result of FediFetcher's activity, it would be a Mastodon issue: FediFetcher just uses the API as intended.

Secondly, because noone else has reported this.

Thirdly, 10k failures out of 28 million jobs, seems perfectly normal.

**Comment by MikeHuntington** [comment] 2023-08-02 03:59
Just an update, after turning the Actions off on my FediFetcher repo, I no longer get the errors in SideKiq. The dead queue is about 30ish entries and none with the error.

So I'm not sure why it only happens when I have FediFetcher enabled.

**Comment by nanos** [comment] 2023-08-02 07:03
Thanks for that update.

I have since asked around on mastodon, and noone else has reported this issue.

I don't know what's causing this, but unfortunately, since this is in sidekiq, which FediFetcher never touches, I don't think I'll be able to do anything about this.

My advice would be to open an issue with Mastodon about this (or ask on the /r/mastodon subreddit, or the #mastoadmin hashtag, or similar), and see if you can get a response there.

If you do, I'd love if you could tag me, as I'd love to learn what's going on here.

However, in the meantime I'm afraid I'm going to close this issue as I do believe this is a mastodon issue.

**Closed by nanos** 2023-08-02 07:03 UTC
